# Generated by Django 5.1.5 on 2025-02-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='course',
            field=models.CharField(choices=[('data_science', 'Data Science & Business Analytics'), ('cyber_security', 'Cyber Security & Ethical Hacking'), ('cloud_devops', 'Cloud & DevOps'), ('chess_analytics', 'Chess Analytics'), ('event_management', 'Event Management'), ('nail_artistry', 'Nail Artistry'), ('makeup_artistry', 'Makeup Artistry'), ('spoken_english', 'Spoken English')], max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='course_category',
            field=models.CharField(choices=[('it', 'IT Courses'), ('professional', 'Professional Courses')], max_length=50),
        ),
    ]
