# Generated by Django 5.1.5 on 2025-02-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_enquiry_course_alter_enquiry_course_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormStyle',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
