# Generated by Django 5.1.5 on 2025-02-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_course_coursecategory_remove_enquiry_course_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='category',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
