# Generated by Django 5.1.5 on 2025-02-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='course_category',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
