# Generated by Django 5.1.5 on 2025-02-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('it', 'IT Courses'), ('professional', 'Professional Courses')], max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('inquiry_message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
