# Generated by Django 5.1.5 on 2025-02-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_inquiry_delete_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('it', 'IT Courses'), ('professional', 'Professional Courses')], max_length=20)),
                ('course', models.CharField(choices=[('data_science', 'Data Science & Business Analytics'), ('cyber_security', 'Cyber Security & Ethical Hacking'), ('cloud_devops', 'Cloud & DevOps'), ('chess_analytics', 'Chess Analytics'), ('event_management', 'Event Management'), ('nail_artistry', 'Nail Artistry'), ('makeup_artistry', 'Makeup Artistry'), ('spoken_english', 'Spoken English')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
