# Generated by Django 5.1.5 on 2025-02-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_enquiry_options_alter_enquiry_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={},
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
