# Generated by Django 5.1.5 on 2025-02-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_contactinfo_countryflag_footerlink_sociallink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='contact_info',
        ),
        migrations.DeleteModel(
            name='CountryFlag',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='contact_links',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='useful_links',
        ),
        migrations.RemoveField(
            model_name='navlink',
            name='parent',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
        migrations.DeleteModel(
            name='NavLink',
        ),
    ]
