# Generated by Django 5.1.5 on 2025-02-11 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_footer_contact_info_delete_countryflag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Upload your footer logo.', null=True, upload_to='footer_logos/')),
                ('address', models.TextField(blank=True, help_text='Enter your office address or other footer text.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Upload your header logo.', null=True, upload_to='header_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='URL or named URL pattern.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines the display order.')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.footer')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='CSS class for the social icon.', max_length=50)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='main.footer')),
            ],
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, help_text="URL or named URL pattern (if using Django's {% url %} tag).", max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines the display order.')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='main.header')),
                ('parent', models.ForeignKey(blank=True, help_text='Leave empty if this is a top-level item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_items', to='main.navitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='E.g., Facebook, Instagram.', max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text="CSS class for the social icon (e.g., 'fab fa-facebook-f').", max_length=50)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='main.header')),
            ],
        ),
    ]
