# Generated by Django 5.1.5 on 2025-02-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_footer_header_footerlink_footersociallink_navitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersociallink',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='navitem',
            name='header',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='header',
        ),
        migrations.RemoveField(
            model_name='navitem',
            name='parent',
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='FooterSocialLink',
        ),
        migrations.DeleteModel(
            name='Header',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.DeleteModel(
            name='NavItem',
        ),
    ]
