# Generated by Django 5.1.5 on 2025-02-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
