# Generated by Django 5.1.5 on 2025-02-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_payment_created_at_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=100)),
                ('key_secret', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
