# Generated by Django 5.1.5 on 2025-02-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('aadhar', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
                ('payment_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
